#!/bin/sh

# load $WALLPAPER_IMAGE environment variable
source $HOME/.config/hypr/scripts/variables/load_envs

function load_wp(){
    swww img -t grow --transition-bezier 0.0,0.0,1.0,1.0 --transition-pos 0.2,1 --transition-duration 3.0 --transition-step 255 --transition-fps 30 $BACKGROUND_IMAGE
}

#perform cleanup and exit
if ! swww query; then
    swww init
fi

load_wp
