#!/bin/bash

hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/themes/apatheia/wallpapers

# wallpaper_location="$(ls $wallpaper_folder | grep .gif | shuf -n 1)"
wallpaper_location="$(ls $wallpaper_folder | grep .jpg | shuf -n 1)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/themes/apatheia/scripts/wallpaper

# dunstify -a "VOLUME" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal

dunstify "Current wallpaper" "$wallpaper_location"
