#!/bin/sh

hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/themes/apatheia/wallpapers

wallpaper_location="$(ls $wallpaper_folder | grep .gif | shuf -n 1)"

echo $wallpaper_location
$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/themes/apatheia/scripts/wallpaper

# swaybg -m fill -i "$HOME/.config/hypr/themes/apatheia/wallpapers/$wallpaper" &
